In [172]:
import pyreadstat
import pandas as pd
from docx import Document
import numpy as np

In [173]:
df = pd.read_csv('/Users/weronika/Desktop/DELab/digital/clusters_new_maps.csv')

In [174]:
clusters = df[['country_i', 'year',
               'ftri_total_i', 'ftri_ict_i', 'ftri_skills_i', 'ftri_rd_i', 'ftri_ind_i', 'ftri_finance_i', 
                'ftri_total_i_s', 'ftri_ict_i_s', 'ftri_skills_i_s','ftri_rd_i_s', 'ftri_ind_i_s', 'ftri_finance_i_s', 
                'sitc_share_all_s', 'reg_score_s',  'serv_va_per_pop_s',  
                 'ht_exp_perc_s', 'ict_pca_index_s']]

In [249]:
clusters_dim = df[['country_i', 'year',
                'cluster_g_3', 'cluster_g_4', 'cluster_g_5']]
# Lista lat do uzupełnienia
fill_years = [2022, 2023, 2024]

# Filtrujemy dane z 2021
df_2021 = clusters_dim[clusters_dim['year'] == 2021]

# Tworzymy kopie wierszy dla nowych lat
copies = []
for year in fill_years:
    df_year = df_2021.copy()
    df_year['year'] = year
    copies.append(df_year)

# Łączymy oryginalny df z nowymi kopiami
clusters_dim_filled = pd.concat([clusters_dim] + copies, ignore_index=True)

# (opcjonalnie) sortujemy
clusters_dim_filled = clusters_dim_filled.sort_values(['country_i', 'year']).reset_index(drop=True)

In [11]:
from sklearn.preprocessing import MinMaxScaler

# Lista zmiennych do skalowania
variables_to_scale = [ 'reg_score', 'sitc_share_all','serv_va_per_pop','ht_exp_perc']

# Skalowanie
scaler = MinMaxScaler()
df_scaled = df.copy()
df_scaled[[v + '_scaled' for v in variables_to_scale]] = scaler.fit_transform(df[variables_to_scale])

## Filling

In [250]:
# Słowniki
country_map = {
    'Bahamas, The': 'Bahamas',
    'Bolivia': 'Bolivia (Plurinational State of)',
    'Congo, Dem. Rep.': 'Dem. Rep. of the Congo',
    'Congo, Rep.': 'Congo',
    'Egypt, Arab Rep.': 'Egypt',
    'Gambia, The': 'Gambia',
    'Hong Kong SAR, China': 'China, Hong Kong SAR',
    'Iran, Islamic Rep.': 'Iran (Islamic Republic of)',
    'Korea, Rep.': 'Republic of Korea',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Lao PDR': "Lao People's Dem. Rep.",
    'Moldova': 'Republic of Moldova',
    'Netherlands': 'Netherlands (Kingdom of the)',
    'Slovak Republic': 'Slovakia',
    'St. Lucia': 'Saint Lucia',
    'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'Tanzania': 'United Republic of Tanzania',
    'Venezuela, RB': 'Venezuela (Bolivarian Rep. of)',
    'Yemen, Rep.': 'Yemen'
}

country_map2 = {
    'Bahamas': 'Bahamas, The',
    'Bolivia (Plurinational State of)': 'Bolivia',
    'China, Hong Kong SAR': 'Hong Kong SAR, China',
    'China, Macao SAR': 'Macao SAR, China',
    'Congo': 'Congo, Rep.',
    'Dem. People\'s Rep. of Korea': "Korea, Dem. People's Rep.",
    'Dem. Rep. of the Congo': 'Congo, Dem. Rep.',
    'Egypt': 'Egypt, Arab Rep.',
    'Gambia': 'Gambia, The',
    'Iran (Islamic Republic of)': 'Iran, Islamic Rep.',
    'Kyrgyzstan': 'Kyrgyz Republic',
    "Lao People's Dem. Rep.": 'Lao PDR',
    'Micronesia (Federated States of)': 'Micronesia, Fed. Sts.',
    'Netherlands (Kingdom of the)': 'Netherlands',
    'Republic of Korea': 'Korea, Rep.',
    'Republic of Moldova': 'Moldova',
    'Saint Kitts and Nevis': 'St. Kitts and Nevis',
    'Saint Lucia': 'St. Lucia',
    'Saint Vincent and the Grenadines': 'St. Vincent and the Grenadines',
    'Slovakia': 'Slovak Republic',
    'State of Palestine': 'West Bank and Gaza',
    'United Republic of Tanzania': 'Tanzania',
    'Venezuela (Bolivarian Rep. of)': 'Venezuela, RB',
    'Yemen': 'Yemen, Rep.'
}

country_map3 = {
    'Bahamas, The': 'Bahamas',
    'Congo, Dem. Rep.': 'Congo (Democratic Republic of the)',
    'Congo, Rep.': 'Congo (Republic of the)',
    "Cote d'Ivoire": "Côte d'Ivoire",
    'Egypt, Arab Rep.': 'Egypt',
    'Gambia, The': 'Gambia',
    'Iran, Islamic Rep.': 'Iran (Islamic Republic of)',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Lao PDR': "Lao People's Democratic Republic",
    'Micronesia, Fed. Sts.': 'Micronesia (Federated States of)',
    'Moldova': 'Moldova (Republic of)',
    'West Bank and Gaza': 'Palestine, State of',
    'Korea, Rep.': 'Republic of Korea',
    'Russian Federation': 'Russia',
    'St. Kitts and Nevis': 'Saint Kitts and Nevis',
    'St. Lucia': 'Saint Lucia',
    'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'Slovak Republic': 'Slovakia',
    'Tanzania': 'Tanzania (United Republic of)',
    'Turkiye': 'Türkiye',
    'United States': 'United States of America',
    'Venezuela, RB': 'Venezuela (Bolivarian Republic of)',
    'Yemen, Rep.': 'Yemen'
}
country_map4 = {
    'Bahamas': 'Bahamas, The',
    'Congo (Democratic Republic of the)': 'Congo, Dem. Rep.',
    'Congo (Republic of the)': 'Congo, Rep.',
    "Côte d'Ivoire": "Cote d'Ivoire",
    'Egypt': 'Egypt, Arab Rep.',
    'Gambia': 'Gambia, The',
    'Iran (Islamic Republic of)': 'Iran, Islamic Rep.',
    'Republic of Korea': 'Korea, Rep.',
    'Kyrgyzstan': 'Kyrgyz Republic',
    "Lao People's Democratic Republic": 'Lao PDR',
    'Moldova (Republic of)': 'Moldova',
    'Russia': 'Russian Federation',
    'Slovakia': 'Slovak Republic',
    'Saint Lucia': 'St. Lucia',
    'Saint Vincent and the Grenadines': 'St. Vincent and the Grenadines',
    'Tanzania (United Republic of)': 'Tanzania',
    'Türkiye': 'Turkiye',
    'United States of America': 'United States',
    'Venezuela (Bolivarian Republic of)': 'Venezuela, RB',
    'Yemen': 'Yemen, Rep.'
}
country_map5 = {
    'Bahamas, The': 'Bahamas',
    'Brunei Darussalam': 'Brunei',
    'Cabo Verde': 'Cape Verde',
    'China, Taiwan Province of': 'Taiwan',
    'Congo, Dem. Rep.': 'Democratic Republic of Congo',
    'Congo, Rep.': 'Congo',
    'Egypt, Arab Rep.': 'Egypt',
    'Gambia, The': 'Gambia',
    'Hong Kong SAR, China': 'Hong Kong',
    'Indonesia (...2002)': 'Indonesia',
    'Iran, Islamic Rep.': 'Iran',
    "Korea, Dem. People's Rep.": 'North Korea',
    'Korea, Rep.': 'South Korea',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Lao PDR': 'Laos',
    'Macao SAR, China': 'Macao',
    'Micronesia (Federated States of)': 'Micronesia (country)',
    'Palestine, State of': 'Palestine',
    'Russian Federation': 'Russia',
    'Slovak Republic': 'Slovakia',
    'St. Lucia': 'Saint Lucia',
    'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'St. Martin (French part)': 'Saint Martin (French part)',
    'Syrian Arab Republic': 'Syria',
    'Timor-Leste': 'East Timor',
    'Turkiye': 'Turkey',
    'Venezuela, RB': 'Venezuela',
    'Viet Nam': 'Vietnam',
    'Virgin Islands (U.S.)': 'United States Virgin Islands',
    'Yemen, Rep.': 'Yemen',
}

In [265]:
country_mapx = {
    'China, Taiwan Province of': 'Taiwan',
    'Indonesia (...2002)': 'Indonesia',
    'Serbia and Montenegro': 'Serbia',  # lub 'Montenegro' – zależnie od struktury docelowej
    'Falkland Islands (Malvinas)': 'Falkland Islands',
    'Netherlands Antilles': 'Curaçao',  # lub 'Sint Maarten' lub inne – zależnie od danych
    'Bonaire, Sint Eustatius and Saba': 'Netherlands',  # zależnie od ujęcia terytorialnego
    'Sudan (...2011)': 'Sudan'
}

country_map_wd = {
    'Bahamas': 'Bahamas, The',
    'Bolivia (Plurinational State of)': 'Bolivia',
    'China, Hong Kong SAR': 'Hong Kong SAR, China',
    'Congo': 'Congo, Rep.',
    'Dem. Rep. of the Congo': 'Congo, Dem. Rep.',
    'Egypt': 'Egypt, Arab Rep.',
    'Gambia': 'Gambia, The',
    'Iran (Islamic Republic of)': 'Iran, Islamic Rep.',
    'Kyrgyzstan': 'Kyrgyz Republic',
    "Lao People's Dem. Rep.": 'Lao PDR',
    'Netherlands (Kingdom of the)': 'Netherlands',
    'Republic of Korea': 'Korea, Rep.',
    'Republic of Moldova': 'Moldova',
    'Saint Lucia': 'St. Lucia',
    'Saint Vincent and the Grenadines': 'St. Vincent and the Grenadines',
    'Slovakia': 'Slovak Republic',
    'United Republic of Tanzania': 'Tanzania',
    'Venezuela (Bolivarian Rep. of)': 'Venezuela, RB',
    'Yemen': 'Yemen, Rep.'
}

In [74]:
# SITC
ex = pd.read_csv('/Users/weronika/Downloads/US.TradeMatrix_1410_20250512_122500.csv')
im = pd.read_csv('/Users/weronika/Downloads/US.TradeMatrix_1410_20250512_122600.csv')
sitc = pd.read_csv('/Users/weronika/Downloads/US.TradeMatrix_20250512_123456.csv')
ex1 = ex[['Economy_Label','Year','TOTAL ALL PRODUCTS_US_at_current_prices_in_thousands_Value','High-skill and technology-intensive manufactures_US_at_current_prices_in_thousands_Value']]
im1 = im[['Economy_Label','Year','TOTAL ALL PRODUCTS_US_at_current_prices_in_thousands_Value','High-skill and technology-intensive manufactures_US_at_current_prices_in_thousands_Value']]
drop = ['Partner_Label']
sitc1 = sitc.drop(columns=drop)
ex1 = ex1.rename(columns={'Year':'year', 'Economy_Label':'country_i','TOTAL ALL PRODUCTS_US_at_current_prices_in_thousands_Value':'tot_ex','High-skill and technology-intensive manufactures_US_at_current_prices_in_thousands_Value':'highskill_ex'})
im1 = im1.rename(columns={'Year':'year', 'Economy_Label':'country_i','TOTAL ALL PRODUCTS_US_at_current_prices_in_thousands_Value':'tot_im','High-skill and technology-intensive manufactures_US_at_current_prices_in_thousands_Value':'highskill_im'})
sitc1 = sitc1.rename(columns={'Year':'year', 'Economy_Label':'country_i','Electrical machinery, apparatus and appliances, n.e.s._Exports_US_at_current_prices_in_thousands_Value':'sitc77_ex','Electrical machinery, apparatus and appliances, n.e.s._Imports_US_at_current_prices_in_thousands_Value':'sitc77_im'})
trade = ex1.merge(im1, on=['country_i', 'year'], how='outer')
trade = trade.merge(sitc1, on=['country_i', 'year'], how='outer')
trade['total_chips_trade'] = trade['sitc77_ex'] + trade['sitc77_im']
trade['total_trade'] = trade['tot_ex'] + trade['tot_im']

# Obliczenie udziału handlu układów scalonych w handlu przemysłowym
trade['sitc_share_all'] = (trade['total_chips_trade'] / trade['total_trade']) * 100

# Opcjonalnie, jeśli chcesz wyczyścić ramkę danych z kolumn tymczasowych:
trade.drop(columns=['total_chips_trade', 'highskill_ex','highskill_im'], inplace=True)

In [255]:
kraje_trade = [
    'American Samoa', 'Andorra', 'Anguilla', 'Antigua and Barbuda', 'Aruba', 'Bermuda', 'Bonaire, Sint Eustatius and Saba', 'British Virgin Islands', 'Cayman Islands', 'Central African Republic', 'Chad', 'China, Macao SAR', 'China, Taiwan Province of', 'Cook Islands', 'Cuba', 'Curacao', "Dem. People's Rep. of Korea", 'Dominica', 'Equatorial Guinea', 'Eritrea', 'Falkland Islands (Malvinas)', 'Faroe Islands', 'French Polynesia', 'Gibraltar', 'Greenland', 'Grenada', 'Guam', 'Indonesia (...2002)', 'Kiribati', 'Liberia', 'Marshall Islands', 'Mayotte', 'Micronesia (Federated States of)', 'Montserrat', 'Nauru', 'Netherlands Antilles', 'New Caledonia', 'Niger', 'Niue', 'Northern Mariana Islands', 'Palau', 'Saint Helena', 'Saint Kitts and Nevis', 'Saint Pierre and Miquelon', 'Serbia and Montenegro', 'Seychelles', 'Sint Maarten (Dutch part)', 'Somalia', 'State of Palestine', 'Syrian Arab Republic', 'Tokelau', 'Tonga', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uzbekistan', 'Wallis and Futuna Islands'
]

# Usuń wskazane kraje
trade01 = trade[~trade['country_i'].isin(kraje_trade)]

In [ ]:
clusters['country_i'] = clusters['country_i'].replace(country_map)
clusters01 = pd.merge(clusters, trade01, on=['country_i','year'], how='outer')

/var/folders/mz/q4b66zqd3xq8pwzks5kk1bkw0000gn/T/ipykernel_1667/2185928716.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clusters['country_i'] = clusters['country_i'].replace(country_map)

In [ ]:
# World bank
worldbank = pd.read_csv('/Users/weronika/Desktop/DELab/74ae9d07-1b8d-4ef4-90cc-aac6d0eff4d9_Data.csv')
worldbank = worldbank.dropna(subset=['Country Name'])
worldbank = worldbank.rename(columns={'Country Name':'country_i', 'Time':'year'}).drop(['Series Code', 'Time Code', 'Country Code'], axis=1)
gdp = worldbank[worldbank['Series Name'] == 'GDP (current US$)']
gdp = gdp.rename(columns={'Value':'gdp_i'}).drop(['Series Name'], axis=1)

gdp_pc = worldbank[worldbank['Series Name'] == 'GDP per capita (current US$)']
gdp_pc = gdp_pc.rename(columns={'Value':'gdppc_i'}).drop(['Series Name'], axis=1)

ht_exp = worldbank[worldbank['Series Name'] == 'High-technology exports (% of manufactured exports)']
ht_exp = ht_exp.rename(columns={'Value':'ht_exp_perc'}).drop(['Series Name'], axis=1)

wd = pd.read_csv('/Users/weronika/Desktop/DELab/1b5e559d-67ba-4b51-aa0e-99961cd03ef4_Data.csv')
wd = wd.dropna(subset=['Country Name'])
wd = wd.rename(columns={'Country Name':'country_i', 'Time':'year'}).drop(['Series Code', 'Time Code','Country Code'], axis=1)

population = wd[wd['Series Name'] == 'Population, total']
population = population.rename(columns={'Value':'population'}).drop(['Series Name'], axis=1)
dataframes = [
    gdp,
    gdp_pc,
    ht_exp,
    serv_va,
    population,
]

# Kolejne mergowanie wszystkich baz po kluczach
from functools import reduce

wd = reduce(lambda left, right: pd.merge(
    left, right, on=['country_i', 'year'], how='outer'
), dataframes)

In [269]:
kraje_wd = ['American Samoa', 'Andorra', 'Antigua and Barbuda', 'Aruba', 'Bermuda', 'British Virgin Islands', 'Cayman Islands', 'Central African Republic', 'Chad', 'Channel Islands', 'Cuba', 'Curacao', 'Dominica', 'Equatorial Guinea', 'Eritrea', 'Faroe Islands', 'French Polynesia', 'Gibraltar', 'Greenland', 'Grenada', 'Guam', 'Isle of Man', 'Kiribati', "Korea, Dem. People's Rep.", 'Kosovo', 'Liberia', 'Liechtenstein', 'Macao SAR, China', 'Marshall Islands', 'Micronesia, Fed. Sts.', 'Monaco', 'Nauru', 'New Caledonia', 'Niger', 'Northern Mariana Islands', 'Palau', 'Puerto Rico', 'San Marino', 'Seychelles', 'Sint Maarten (Dutch part)', 'Somalia', 'St. Kitts and Nevis', 'St. Martin (French part)', 'Syrian Arab Republic', 'Tonga', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uzbekistan', 'Virgin Islands (U.S.)', 'West Bank and Gaza']
wd01 = wd[~wd['country_i'].isin(kraje_wd)]

In [270]:
wd02 = wd01[wd01['year'] > 2007]
clusters01['country_i'] = clusters01['country_i'].replace(country_map_wd)
clusters02 = pd.merge(clusters01, wd01, on=['country_i','year'], how='outer')

In [23]:
reg = pd.read_excel('/Users/weronika/Desktop/DELab/data/ITU-ICT.xlsx')
reg1 = reg[reg['Indicator']=='ICT Regulatory Tracker - Overall Score']

col=['Economy Name','Indicator ID','Indicator','Attribute 1','Attribute 2','Attribute 3','Partner']
reg2 = reg1.drop(columns=col)

reg_m = reg2.melt(id_vars=['Economy ISO3'], var_name='year', value_name='reg_score_d')
regm1 = reg_m.rename(columns={'Economy ISO3':'iso3_d'})
regm1["year"] = pd.to_numeric(regm1["year"], errors='ignore')

reg_m = reg2.melt(id_vars=['Economy ISO3'], var_name='year', value_name='reg_score')
regm1 = reg_m.rename(columns={'Economy ISO3':'iso3_o'})
regm1["year"] = pd.to_numeric(regm1["year"], errors='ignore')

iso3_to_country = {
    'AFG': 'Afghanistan',
    'AGO': 'Angola',
    'ALB': 'Albania',
    'AND': 'Andorra',
    'ARE': 'United Arab Emirates',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'ATG': 'Antigua and Barbuda',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'AZE': 'Azerbaijan',
    'BDI': 'Burundi',
    'BEL': 'Belgium',
    'BEN': 'Benin',
    'BFA': 'Burkina Faso',
    'BGD': 'Bangladesh',
    'BGR': 'Bulgaria',
    'BHR': 'Bahrain',
    'BHS': 'Bahamas',
    'BIH': 'Bosnia and Herzegovina',
    'BLR': 'Belarus',
    'BLZ': 'Belize',
    'BOL': 'Bolivia',
    'BRA': 'Brazil',
    'BRB': 'Barbados',
    'BRN': 'Brunei Darussalam',
    'BTN': 'Bhutan',
    'BWA': 'Botswana',
    'CAF': 'Central African Republic',
    'CAN': 'Canada',
    'CHE': 'Switzerland',
    'CHL': 'Chile',
    'CHN': 'China',
    'CIV': "Côte d'Ivoire",
    'CMR': 'Cameroon',
    'COD': 'Congo (Democratic Republic of the)',
    'COG': 'Congo (Republic of the)',
    'COL': 'Colombia',
    'COM': 'Comoros',
    'CPV': 'Cabo Verde',
    'CRI': 'Costa Rica',
    'CUB': 'Cuba',
    'CYP': 'Cyprus',
    'CZE': 'Czechia',
    'DEU': 'Germany',
    'DJI': 'Djibouti',
    'DMA': 'Dominica',
    'DNK': 'Denmark',
    'DOM': 'Dominican Republic',
    'DZA': 'Algeria',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'ERI': 'Eritrea',
    'ESP': 'Spain',
    'EST': 'Estonia',
    'ETH': 'Ethiopia',
    'FIN': 'Finland',
    'FJI': 'Fiji',
    'FRA': 'France',
    'FSM': 'Micronesia (Federated States of)',
    'GAB': 'Gabon',
    'GBR': 'United Kingdom',
    'GEO': 'Georgia',
    'GHA': 'Ghana',
    'GIN': 'Guinea',
    'GMB': 'Gambia',
    'GNB': 'Guinea-Bissau',
    'GNQ': 'Equatorial Guinea',
    'GRC': 'Greece',
    'GRD': 'Grenada',
    'GTM': 'Guatemala',
    'GUY': 'Guyana',
    'HKG': 'Hong Kong SAR, China',
    'HND': 'Honduras',
    'HRV': 'Croatia',
    'HTI': 'Haiti',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'IND': 'India',
    'IRL': 'Ireland',
    'IRN': 'Iran (Islamic Republic of)',
    'IRQ': 'Iraq',
    'ISL': 'Iceland',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JOR': 'Jordan',
    'JPN': 'Japan',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'KGZ': 'Kyrgyzstan',
    'KHM': 'Cambodia',
    'KIR': 'Kiribati',
    'KNA': 'Saint Kitts and Nevis',
    'KOR': 'Republic of Korea',
    'KWT': 'Kuwait',
    'LAO': "Lao People's Democratic Republic",
    'LBN': 'Lebanon',
    'LBR': 'Liberia',
    'LBY': 'Libya',
    'LCA': 'Saint Lucia',
    'LIE': 'Liechtenstein',
    'LKA': 'Sri Lanka',
    'LSO': 'Lesotho',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'LVA': 'Latvia',
    'MAR': 'Morocco',
    'MCO': 'Monaco',
    'MDA': 'Moldova (Republic of)',
    'MDG': 'Madagascar',
    'MDV': 'Maldives',
    'MEX': 'Mexico',
    'MHL': 'Marshall Islands',
    'MKD': 'North Macedonia',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MMR': 'Myanmar',
    'MNE': 'Montenegro',
    'MNG': 'Mongolia',
    'MOZ': 'Mozambique',
    'MRT': 'Mauritania',
    'MUS': 'Mauritius',
    'MWI': 'Malawi',
    'MYS': 'Malaysia',
    'NAM': 'Namibia',
    'NER': 'Niger',
    'NGA': 'Nigeria',
    'NIC': 'Nicaragua',
    'NLD': 'Netherlands',
    'NOR': 'Norway',
    'NPL': 'Nepal',
    'NRU': 'Nauru',
    'NZL': 'New Zealand',
    'OMN': 'Oman',
    'PAK': 'Pakistan',
    'PAN': 'Panama',
    'PER': 'Peru',
    'PHL': 'Philippines',
    'PNG': 'Papua New Guinea',
    'POL': 'Poland',
    'PRT': 'Portugal',
    'PRY': 'Paraguay',
    'PSE': 'Palestine, State of',
    'QAT': 'Qatar',
    'ROU': 'Romania',
    'RUS': 'Russia',
    'RWA': 'Rwanda',
    'SAU': 'Saudi Arabia',
    'SDN': 'Sudan',
    'SEN': 'Senegal',
    'SGP': 'Singapore',
    'SLB': 'Solomon Islands',
    'SLE': 'Sierra Leone',
    'SLV': 'El Salvador',
    'SMR': 'San Marino',
    'SOM': 'Somalia',
    'SRB': 'Serbia',
    'SSD': 'South Sudan',
    'STP': 'Sao Tome and Principe',
    'SUR': 'Suriname',
    'SVK': 'Slovakia',
    'SVN': 'Slovenia',
    'SWE': 'Sweden',
    'SWZ': 'Eswatini',
    'SYC': 'Seychelles',
    'SYR': 'Syrian Arab Republic',
    'TCD': 'Chad',
    'TGO': 'Togo',
    'THA': 'Thailand',
    'TJK': 'Tajikistan',
    'TKM': 'Turkmenistan',
    'TLS': 'Timor-Leste',
    'TON': 'Tonga',
    'TTO': 'Trinidad and Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Türkiye',
    'TUV': 'Tuvalu',
    'TZA': 'Tanzania (United Republic of)',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'URY': 'Uruguay',
    'USA': 'United States of America',
    'UZB': 'Uzbekistan',
    'VCT': 'Saint Vincent and the Grenadines',
    'VEN': 'Venezuela (Bolivarian Republic of)',
    'VNM': 'Viet Nam',
    'VUT': 'Vanuatu',
    'WSM': 'Samoa',
    'YEM': 'Yemen',
    'ZAF': 'South Africa',
    'ZMB': 'Zambia',
    'ZWE': 'Zimbabwe'
}
regm1['country_i'] = regm1['iso3_o'].map(iso3_to_country)

/var/folders/mz/q4b66zqd3xq8pwzks5kk1bkw0000gn/T/ipykernel_1667/3081286060.py:9: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  regm1["year"] = pd.to_numeric(regm1["year"], errors='ignore')
/var/folders/mz/q4b66zqd3xq8pwzks5kk1bkw0000gn/T/ipykernel_1667/3081286060.py:13: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  regm1["year"] = pd.to_numeric(regm1["year"], errors='ignore')

In [274]:
regm01 = regm1[regm1['year'] > 2007]
clusters02['country_i'] = clusters02['country_i'].replace(country_map3)
kraje_reg = ['Andorra', 'Antigua and Barbuda', 'Central African Republic', 'Chad', 'Cuba', 'Dominica', 'Equatorial Guinea', 'Eritrea', 'Grenada', 'Kiribati', 'Liberia', 'Liechtenstein', 'Marshall Islands', 'Micronesia (Federated States of)', 'Monaco', 'Nauru', 'Niger', 'Palestine, State of', 'Saint Kitts and Nevis', 'San Marino', 'Seychelles', 'Somalia', 'Syrian Arab Republic', 'Tonga', 'Turkmenistan', 'Tuvalu', 'Uzbekistan']
regm02 = regm01[~regm01['country_i'].isin(kraje_reg)]
clusters03 = pd.merge(clusters02, regm02, on=['country_i','year'], how='outer')

In [288]:
data_countries = set(clusters04['country_i'].unique())
empl_countries = set(connection01['country_i'].unique())

data_only = data_countries - empl_countries
empl_only = empl_countries - data_countries

# Znajdź dopasowane nazwy krajów
common_countries = data_countries.intersection(empl_countries)
print(f"Dopasowane nazwy krajów ({len(common_countries)}):")
print(sorted(common_countries))


print(f"\nNazwy krajów tylko w zbiorze 'data' ({len(data_only)}):")
print(sorted(data_only))

print(f"\nNazwy krajów tylko w zbiorze 'merged' ({len(empl_only)}):")
print(sorted(empl_only))

Dopasowane nazwy krajów (166):
['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Korea, Rep.', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latvia', 'Lebanon', 'Lesotho', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia', 'Solomon Islands', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Lucia', 'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Vanuatu', 'Venezuela, RB', 'Viet Nam', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']

Nazwy krajów tylko w zbiorze 'data' (0):
[]

Nazwy krajów tylko w zbiorze 'merged' (51):
['American Samoa', 'Andorra', 'Antigua and Barbuda', 'Aruba', 'Bermuda', 'British Virgin Islands', 'Cayman Islands', 'Central African Republic', 'Chad', 'Channel Islands', 'Cuba', 'Curacao', 'Dominica', 'Equatorial Guinea', 'Eritrea', 'Faroe Islands', 'French Polynesia', 'Gibraltar', 'Greenland', 'Grenada', 'Guam', 'Isle of Man', 'Kiribati', "Korea, Dem. People's Rep.", 'Kosovo', 'Liberia', 'Liechtenstein', 'Macao SAR, China', 'Marshall Islands', 'Micronesia, Fed. Sts.', 'Monaco', 'Nauru', 'New Caledonia', 'Niger', 'Northern Mariana Islands', 'Palau', 'Puerto Rico', 'San Marino', 'Seychelles', 'Sint Maarten (Dutch part)', 'Somalia', 'St. Kitts and Nevis', 'St. Martin (French part)', 'Syrian Arab Republic', 'Tonga', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uzbekistan', 'Virgin Islands (U.S.)', 'West Bank and Gaza']

In [276]:
import pandas as pd
import requests
# Fetch the data.
dfinc = pd.read_csv("https://ourworldindata.org/grapher/world-bank-income-groups.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})
# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/world-bank-income-groups.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()
income = dfinc.rename(columns={'Entity':'country_i','Year':'year'})

In [279]:
country_map_inc = {
    'Congo (Democratic Republic of the)': 'Democratic Republic of Congo',
    'Congo (Republic of the)': 'Congo',
    "Côte d'Ivoire": "Cote d'Ivoire",
    'Iran (Islamic Republic of)': 'Iran',
    "Lao People's Democratic Republic": 'Laos',
    'Moldova (Republic of)': 'Moldova',
    'Republic of Korea': 'South Korea',
    'Tanzania (United Republic of)': 'Tanzania',
    'Türkiye': 'Turkey',
    'United States of America': 'United States',
    'Venezuela (Bolivarian Republic of)': 'Venezuela'
}

In [282]:
clusters03['country_i'] = clusters03['country_i'].replace(country_map5)
clusters03['country_i'] = clusters03['country_i'].replace(country_map_inc)
income01 = income[income['year'] > 2007]
kraje_inc = ['American Samoa', 'Andorra', 'Antigua and Barbuda', 'Aruba', 'Bermuda', 'British Virgin Islands', 'Cayman Islands', 'Central African Republic', 'Chad', 'Channel Islands', 'Cuba', 'Curacao', 'Dominica', 'Equatorial Guinea', 'Eritrea', 'Faroe Islands', 'French Guiana', 'French Polynesia', 'French Southern Territories', 'Gibraltar', 'Greenland', 'Grenada', 'Guam', 'Isle of Man', 'Kiribati', 'Kosovo', 'Liberia', 'Liechtenstein', 'Macao', 'Marshall Islands', 'Mayotte', 'Micronesia (country)', 'Monaco', 'Nauru', 'Netherlands Antilles', 'New Caledonia', 'Niger', 'North Korea', 'Northern Mariana Islands', 'Palau', 'Palestine', 'Puerto Rico', 'Saint Kitts and Nevis', 'Saint Martin (French part)', 'San Marino', 'Seychelles', 'Sint Maarten (Dutch part)', 'Somalia', 'Syria', 'Taiwan', 'Tonga', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'United States Virgin Islands', 'Uzbekistan']
income02 = income01[~income01['country_i'].isin(kraje_inc)]
clusters04 = pd.merge(clusters03, income02, on=['country_i','year'], how='outer')
clusters04['year'] = clusters04['year'].astype(int)

In [152]:
# new
drop = ['Code']
income02 = income01.drop(columns=drop).rename(columns={'classification':'income'})

In [27]:
# connection
wdi = pd.read_csv('/Users/weronika/Desktop/DELab/38dcd351-0c40-4c62-be46-16279c6d3b6c_Data.csv')
wdi = wdi.dropna(subset=['Country Name'])
wdi = wdi.rename(columns={'Country Name':'country_i', 'Time':'year'}).drop(['Series Code', 'Time Code', 'Country Code'], axis=1)
wdi
broadband = wdi[wdi['Series Name'] == 'Fixed broadband subscriptions']
broadband = broadband.rename(columns={'Value':'broadband_i'}).drop(['Series Name'], axis=1)
users = wdi[wdi['Series Name'] == 'Individuals using the Internet (% of population)']
users = users.rename(columns={'Value':'internet_users_i'}).drop(['Series Name'], axis=1)
serv = wdi[wdi['Series Name'] == 'Secure Internet servers']
serv = serv.rename(columns={'Value':'secure_servers_i'}).drop(['Series Name'], axis=1)

dataframes = [
    broadband,
    users,
    serv
]

# Kolejne mergowanie wszystkich baz po kluczach
from functools import reduce

connection = reduce(lambda left, right: pd.merge(
    left, right, on=['country_i', 'year'], how='outer'
), dataframes)

connection = connection.dropna(subset=['year'])  # usuń wiersze z NaN w 'year'
connection['year'] = connection['year'].astype(int)

In [286]:
country_map_conn = {
    'Bahamas': 'Bahamas, The',
    'Brunei': 'Brunei Darussalam',
    'Cape Verde': 'Cabo Verde',
    'Congo': 'Congo, Rep.',
    'Democratic Republic of Congo': 'Congo, Dem. Rep.',
    'East Timor': 'Timor-Leste',
    'Egypt': 'Egypt, Arab Rep.',
    'Gambia': 'Gambia, The',
    'Hong Kong': 'Hong Kong SAR, China',
    'Iran': 'Iran, Islamic Rep.',
    'Kyrgyzstan': 'Kyrgyz Republic',
    'Laos': 'Lao PDR',
    'Russia': 'Russian Federation',
    'Saint Lucia': 'St. Lucia',
    'Saint Vincent and the Grenadines': 'St. Vincent and the Grenadines',
    'Slovakia': 'Slovak Republic',
    'South Korea': 'Korea, Rep.',
    'Turkey': 'Turkiye',
    'Venezuela': 'Venezuela, RB',
    'Vietnam': 'Viet Nam',
    'Yemen': 'Yemen, Rep.'
}

In [289]:
connection01 = connection[connection['year'] > 2007]
clusters04['country_i'] = clusters04['country_i'].replace(country_map_conn)
kraje_conn = ['American Samoa', 'Andorra', 'Antigua and Barbuda', 'Aruba', 'Bermuda', 'British Virgin Islands', 'Cayman Islands', 'Central African Republic', 'Chad', 'Channel Islands', 'Cuba', 'Curacao', 'Dominica', 'Equatorial Guinea', 'Eritrea', 'Faroe Islands', 'French Polynesia', 'Gibraltar', 'Greenland', 'Grenada', 'Guam', 'Isle of Man', 'Kiribati', "Korea, Dem. People's Rep.", 'Kosovo', 'Liberia', 'Liechtenstein', 'Macao SAR, China', 'Marshall Islands', 'Micronesia, Fed. Sts.', 'Monaco', 'Nauru', 'New Caledonia', 'Niger', 'Northern Mariana Islands', 'Palau', 'Puerto Rico', 'San Marino', 'Seychelles', 'Sint Maarten (Dutch part)', 'Somalia', 'St. Kitts and Nevis', 'St. Martin (French part)', 'Syrian Arab Republic', 'Tonga', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uzbekistan', 'Virgin Islands (U.S.)', 'West Bank and Gaza']
connection02 = connection01[~connection01['country_i'].isin(kraje_conn)]
clusters05 = pd.merge(clusters04, connection02, on=['country_i','year'], how='outer')

In [291]:
# Oblicz procent NaN dla każdego kraju
nan_per_country = (
    clusters05
    .set_index('country_i')
    .isna()
    .groupby('country_i')
    .mean()
    .mean(axis=1)
    .sort_values(ascending=False) * 100
).round(2)

# Wyświetl top 10 krajów z największym procentem braków
pd.set_option('display.max_rows', None) 
nan_per_country

country_i
South Sudan                       51.39
Sudan                             45.48
Venezuela, RB                     35.00
Haiti                             30.42
Iraq                              30.28
Vanuatu                           30.00
Sierra Leone                      29.17
Timor-Leste                       28.89
Serbia                            28.47
Libya                             28.33
Yemen, Rep.                       28.33
Guinea-Bissau                     27.92
Congo, Rep.                       27.50
Djibouti                          27.22
Papua New Guinea                  26.94
Tajikistan                        26.67
Afghanistan                       26.67
Guinea                            26.53
Solomon Islands                   26.39
Congo, Dem. Rep.                  26.39
Bhutan                            26.25
Barbados                          26.11
Mauritania                        25.97
Mali                              25.97
Philippines                       25.97
Lebanon                           25.97
Myanmar                           25.97
Sri Lanka                         25.97
Maldives                          25.83
Comoros                           25.83
St. Lucia                         25.69
Bangladesh                        25.69
Kenya                             25.69
Uganda                            25.56
Morocco                           25.56
Cameroon                          25.56
Kuwait                            25.56
Qatar                             25.56
Lesotho                           25.42
Angola                            25.42
Burundi                           25.28
Sao Tome and Principe             25.28
Ethiopia                          25.14
Samoa                             25.14
Mongolia                          25.14
Mozambique                        25.14
Iran, Islamic Rep.                25.14
Lao PDR                           25.14
Botswana                          25.14
Cabo Verde                        25.14
Benin                             25.14
Algeria                           25.14
Armenia                           25.14
Cote d'Ivoire                     25.00
India                             25.00
Honduras                          25.00
Gambia, The                       25.00
Saudi Arabia                      24.86
Guatemala                         24.86
Guyana                            24.86
Belize                            24.86
Suriname                          24.86
Oman                              24.86
Nigeria                           24.86
Gabon                             24.86
Nepal                             24.86
Ukraine                           24.86
Ghana                             24.86
United Arab Emirates              24.86
Cambodia                          24.72
Russian Federation                24.72
Burkina Faso                      24.72
Indonesia                         24.72
Bahrain                           24.72
Rwanda                            24.72
Belarus                           24.72
Malaysia                          24.58
Brunei Darussalam                 24.58
Moldova                           24.58
Albania                           24.58
Canada                            24.58
Kazakhstan                        24.58
Fiji                              24.58
St. Vincent and the Grenadines    24.58
Bahamas, The                      24.58
Viet Nam                          24.58
Bolivia                           24.44
Bosnia and Herzegovina            24.44
Trinidad and Tobago               24.44
Zambia                            24.44
United States                     24.44
Tunisia                           24.44
New Zealand                       24.44
Tanzania                          24.44
Togo                              24.44
Senegal                           24.44
Pakistan                          24.44
Panama                            24.44
Peru                              24.44
Montenegro                        24.44
Eswatini                          24.44
Zimbabwe                          24.44
Mexico                            24.44
Egypt, Arab Rep.                  24.44
Mauritius                         24.44
Jamaica                           24.44
Malawi                            24.44
Kyrgyz Republic                   24.44
Georgia                           24.44
Luxembourg                        24.31
Uruguay                           24.31
Italy                             24.31
Jordan                            24.31
Singapore                         24.31
Finland                           24.31
France                            24.31
Belgium                           24.31
Spain                             24.31
Dominican Republic                24.31
Ireland                           24.31
United Kingdom                    24.31
Sweden                            24.31
Korea, Rep.                       24.31
Ecuador                           24.31
Argentina                         24.31
El Salvador                       24.31
Hong Kong SAR, China              24.31
Slovenia                          24.31
Cyprus                            24.31
Lithuania                         24.31
Chile                             24.31
Namibia                           24.31
Malta                             24.31
Estonia                           24.31
China                             24.31
Nicaragua                         24.31
Colombia                          24.31
North Macedonia                   24.31
Norway                            24.31
Madagascar                        24.31
Bulgaria                          24.31
Netherlands                       24.31
Latvia                            24.31
Croatia                           24.31
Costa Rica                        24.31
Poland                            24.31
Romania                           24.31
Portugal                          24.31
Israel                            24.31
Japan                             24.31
Denmark                           24.17
Slovak Republic                   24.17
Austria                           24.17
Hungary                           24.17
Germany                           24.17
Brazil                            24.17
Greece                            24.17
Australia                         24.17
South Africa                      24.17
Paraguay                          24.17
Thailand                          24.17
Czechia                           24.17
Azerbaijan                        24.17
Switzerland                       24.17
Iceland                           24.17
Turkiye                           24.03
dtype: float64

## Imputation

In [298]:
drop = ['Code','iso3_o']
clusters_cd = clusters05.drop(columns=drop)
# Przenieś kolumnę 'classification' na początek
cols = ['classification'] + [col for col in clusters_cd.columns if col != 'classification']
clusters_cd = clusters_cd[cols]
clusters_cd = clusters_cd[clusters_cd['year'] > 2007]

In [299]:
# Cold desk imputation

df_imputed = clusters_cd.copy()

# Pomijamy kolumny 'country_i' i 'year'
for col in df_imputed.columns:
    if col not in ['country_i', 'year','classification']:
        df_imputed[col] = pd.to_numeric(df_imputed[col], errors='coerce')


for col in df_imputed.columns[2:]:  # pomijamy 'country' i 'year'
    # Średnia wartość dla każdego kraju (bez NaN)
    country_means = df_imputed.groupby('country_i')[col].transform('mean')

    # Uzupełnienie braków średnią z danego kraju
    df_imputed[col] = df_imputed[col].fillna(country_means)

    # Fallback: średnia globalna, jeśli kraj nie ma żadnych danych
    df_imputed[col] = df_imputed[col].fillna(df_imputed[col].mean())

In [305]:

data_countries = set(df_imputed['country_i'].unique())
empl_countries = set(clusters_dim_filled['country_i'].unique())

data_only = data_countries - empl_countries
empl_only = empl_countries - data_countries

# Znajdź dopasowane nazwy krajów
common_countries = data_countries.intersection(empl_countries)
print(f"Dopasowane nazwy krajów ({len(common_countries)}):")
print(sorted(common_countries))


print(f"\nNazwy krajów tylko w zbiorze 'data' ({len(data_only)}):")
print(sorted(data_only))

print(f"\nNazwy krajów tylko w zbiorze 'merged' ({len(empl_only)}):")
print(sorted(empl_only))

Dopasowane nazwy krajów (166):
['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Korea, Rep.', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latvia', 'Lebanon', 'Lesotho', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia', 'Solomon Islands', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Lucia', 'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Vanuatu', 'Venezuela, RB', 'Viet Nam', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']

Nazwy krajów tylko w zbiorze 'data' (0):
[]

Nazwy krajów tylko w zbiorze 'merged' (0):
[]

In [304]:
country_map = {
    'Sudan (...2011)':'South Sudan'
}
clusters_dim_filled['country_i'] = clusters_dim_filled['country_i'].replace(country_map)

In [309]:
clusters_all01 = pd.merge(df_imputed, clusters_dim_filled, on=['country_i','year'], how='outer')

In [329]:
clusters_all01.columns

Index(['classification', 'country_i', 'year', 'ftri_total_i', 'ftri_ict_i',
       'ftri_skills_i', 'ftri_rd_i', 'ftri_ind_i', 'ftri_finance_i',
       'ftri_total_i_s', 'ftri_ict_i_s', 'ftri_skills_i_s', 'ftri_rd_i_s',
       'ftri_ind_i_s', 'ftri_finance_i_s', 'sitc_share_all_s', 'reg_score_s',
       'serv_va_per_pop_s', 'ht_exp_perc_s', 'ict_pca_index_s', 'tot_ex',
       'tot_im', 'sitc77_ex', 'sitc77_im', 'total_trade', 'sitc_share_all',
       'gdp_i', 'gdppc_i', 'ht_exp_perc', 'serv_va_perc', 'population',
       'reg_score', 'broadband_i', 'internet_users_i', 'secure_servers_i',
       'cluster_g_3', 'cluster_g_4', 'cluster_g_5'],
      dtype='object')

In [346]:
# Cold desk imputation

df_imputed1 = clusters_all02.copy()

# Pomijamy kolumny 'country_i' i 'year'
for col in df_imputed1.columns:
    if col not in ['country_i', 'year','classification']:
        df_imputed1[col] = pd.to_numeric(df_imputed1[col], errors='coerce')


for col in df_imputed1.columns[2:]:  # pomijamy 'country' i 'year'
    # Średnia wartość dla każdego kraju (bez NaN)
    country_means = df_imputed1.groupby('country_i')[col].transform('mean')

    # Uzupełnienie braków średnią z danego kraju
    df_imputed1[col] = df_imputed1[col].fillna(country_means)

    # Fallback: średnia globalna, jeśli kraj nie ma żadnych danych
    df_imputed1[col] = df_imputed1[col].fillna(df_imputed1[col].mean())

In [347]:
df_imputed1.to_csv('/Users/weronika/Desktop/DELab/digital/clusters_world.csv')

In [310]:
clusters_all01['year'].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024])

## Cluster adjust

In [312]:
# Lista krajów do przesunięcia z klastra 3 → 2
cluster3_to_2 = ['Kazakhstan', 'Malaysia', 'Mexico']

# Lista krajów do przesunięcia z klastra 3 lub 2 → 1
to_cluster1 = [
    'Philippines', 'Vietnam', 'Armenia', 'Ghana', 'Nigeria', 'India', 'Pakistan',
    'Egypt, Arab Rep.', 'Honduras', 
]

# Aktualizacja klastra: 3 → 2
clusters_all01.loc[
    (clusters_all01['year'] == 2015) &
    (clusters_all01['country_i'].isin(cluster3_to_2)) &
    (clusters_all01['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all01.loc[
    (clusters_all01['year'] == 2015) &
    (clusters_all01['country_i'].isin(to_cluster1)) &
    (clusters_all01['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

In [313]:
# Lista krajów do przesunięcia z klastra 3 → 2
cluster3_to_2_2014 = ['Kazakhstan', 'Malaysia', 'Mexico']

# Lista krajów do przesunięcia z klastra 3 lub 2 → 1
to_cluster1_2014 = [
    'Philippines', 'Vietnam', 'Armenia', 'Ghana', 'Nigeria',
    'India', 'Pakistan', 'Egypt, Arab Rep.', 'Honduras'
]

# Przesunięcie z klastra 3 → 2
clusters_all01.loc[
    (clusters_all01['year'] == 2014) &
    (clusters_all01['country_i'].isin(cluster3_to_2_2014)) &
    (clusters_all01['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Przesunięcie z klastra 3 lub 2 → 1
clusters_all01.loc[
    (clusters_all01['year'] == 2014) &
    (clusters_all01['country_i'].isin(to_cluster1_2014)) &
    (clusters_all01['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

In [316]:
# Lista krajów do przesunięcia z klastra 3 → 2
cluster3_to_2_2013 = ['Kazakhstan', 'Malaysia', 'Mexico']

# Lista krajów do przesunięcia z klastra 3 lub 2 → 1
to_cluster1_2013 = [
    'Philippines', 'Vietnam', 'Armenia', 'Ghana', 'Nigeria',
    'India', 'Pakistan', 'Egypt, Arab Rep.', 'Honduras'
]

# Przesunięcie z klastra 3 → 2
clusters_all01.loc[
    (clusters_all01['year'] == 2013) &
    (clusters_all01['country_i'].isin(cluster3_to_2_2013)) &
    (clusters_all01['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Przesunięcie z klastra 3 lub 2 → 1
clusters_all01.loc[
    (clusters_all01['year'] == 2013) &
    (clusters_all01['country_i'].isin(to_cluster1_2013)) &
    (clusters_all01['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

In [345]:
# Lista krajów do przesunięcia z klastra 3 → 2
cluster3_to_2_2012 = [ 'Malaysia', 'Mexico']

# Lista krajów do przesunięcia z klastra 3 lub 2 → 1
to_cluster1_2012 = [
    'Philippines', 'Vietnam', 'Armenia', 'Ghana', 'Nigeria',
    'India', 'Pakistan', 'Egypt, Arab Rep.', 'Honduras','Rwanda'
]

# Przesunięcie z klastra 3 → 2
clusters_all01.loc[
    (clusters_all01['year'] == 2012) &
    (clusters_all01['country_i'].isin(cluster3_to_2_2012)) &
    (clusters_all01['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Przesunięcie z klastra 3 lub 2 → 1
clusters_all01.loc[
    (clusters_all01['year'] == 2012) &
    (clusters_all01['country_i'].isin(to_cluster1_2012)) &
    (clusters_all01['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

In [318]:
# Lista krajów do przesunięcia z klastra 3 → 2
cluster3_to_2_2011 = [ 'Malaysia', 'Mexico']

# Lista krajów do przesunięcia z klastra 3 lub 2 → 1
to_cluster1_2011 = [
    'Philippines', 'Vietnam', 'Armenia', 'Ghana', 'Nigeria',
    'India', 'Pakistan', 'Egypt, Arab Rep.', 'Honduras'
]

# Przesunięcie z klastra 3 → 2
clusters_all01.loc[
    (clusters_all01['year'] == 2011) &
    (clusters_all01['country_i'].isin(cluster3_to_2_2011)) &
    (clusters_all01['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Przesunięcie z klastra 3 lub 2 → 1
clusters_all01.loc[
    (clusters_all01['year'] == 2011) &
    (clusters_all01['country_i'].isin(to_cluster1_2011)) &
    (clusters_all01['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

In [319]:
# Lista krajów do przesunięcia z klastra 3 → 2
cluster3_to_2_2010 = [ 'Malaysia', 'Mexico']

# Lista krajów do przesunięcia z klastra 3 lub 2 → 1
to_cluster1_2010 = [
    'Philippines', 'Vietnam', 'Armenia', 'Ghana', 'Nigeria',
    'India', 'Pakistan', 'Egypt, Arab Rep.', 'Honduras'
]

# Przesunięcie z klastra 3 → 2
clusters_all01.loc[
    (clusters_all01['year'] == 2010) &
    (clusters_all01['country_i'].isin(cluster3_to_2_2010)) &
    (clusters_all01['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Przesunięcie z klastra 3 lub 2 → 1
clusters_all01.loc[
    (clusters_all01['year'] == 2010) &
    (clusters_all01['country_i'].isin(to_cluster1_2010)) &
    (clusters_all01['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

In [241]:
# Lista krajów do przesunięcia z klastra 3 → 2
cluster3_to_2_2011 = [ 'Malaysia', 'Mexico']

# Lista krajów do przesunięcia z klastra 3 lub 2 → 1
to_cluster1_2011 = [
    'Philippines', 'Vietnam', 'Armenia', 'Ghana', 'Nigeria',
    'India', 'Pakistan', 'Egypt, Arab Rep.', 'Honduras'
]

# Przesunięcie z klastra 3 → 2
clusters_all01.loc[
    (clusters_all01['year'] == 2011) &
    (clusters_all01['country_i'].isin(cluster3_to_2_2011)) &
    (clusters_all01['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Przesunięcie z klastra 3 lub 2 → 1
clusters_all01.loc[
    (clusters_all01['year'] == 2011) &
    (clusters_all01['country_i'].isin(to_cluster1_2011)) &
    (clusters_all01['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

In [320]:
# Lista krajów do przesunięcia z klastra 3 → 2
cluster3_to_2_2009 = [ 'Malaysia', 'Mexico']

# Lista krajów do przesunięcia z klastra 3 lub 2 → 1
to_cluster1_2009 = [
    'Philippines', 'Vietnam', 'Armenia', 'Ghana', 'Nigeria',
    'India', 'Pakistan', 'Egypt, Arab Rep.', 'Honduras'
]

# Przesunięcie z klastra 3 → 2
clusters_all01.loc[
    (clusters_all01['year'] == 2009) &
    (clusters_all01['country_i'].isin(cluster3_to_2_2009)) &
    (clusters_all01['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Przesunięcie z klastra 3 lub 2 → 1
clusters_all01.loc[
    (clusters_all01['year'] == 2009) &
    (clusters_all01['country_i'].isin(to_cluster1_2009)) &
    (clusters_all01['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

In [321]:
# Lista krajów do przesunięcia z klastra 3 → 2
cluster3_to_2_2008 = [ 'Malaysia', 'Mexico']

# Lista krajów do przesunięcia z klastra 3 lub 2 → 1
to_cluster1_2008 = [
    'Philippines', 'Vietnam', 'Armenia', 'Ghana', 'Nigeria',
    'India', 'Pakistan', 'Egypt, Arab Rep.', 'Honduras'
]

# Przesunięcie z klastra 3 → 2
clusters_all01.loc[
    (clusters_all01['year'] == 2008) &
    (clusters_all01['country_i'].isin(cluster3_to_2_2008)) &
    (clusters_all01['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Przesunięcie z klastra 3 lub 2 → 1
clusters_all01.loc[
    (clusters_all01['year'] == 2008) &
    (clusters_all01['country_i'].isin(to_cluster1_2008)) &
    (clusters_all01['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

In [338]:
clusters_all02['country_i'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The',
       'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
       'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Chile', 'China', 'Colombia', 'Comoros',
       'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire",
       'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti',
       'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador',
       'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Honduras', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Israel',
       'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya',
       'Korea, Rep.', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latvia',
       'Lebanon', 'Lesotho', 'Libya', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Nigeria',
       'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda',
       'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Sierra Leone', 'Singapore', 'Slovak Republic',
       'Slovenia', 'Solomon Islands', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'St. Lucia',
       'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste',
       'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Uganda',
       'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Uruguay', 'Vanuatu', 'Venezuela, RB', 'Viet Nam',
       'Yemen, Rep.', 'Zambia', 'Zimbabwe'], dtype=object)

In [341]:
# Lista krajów do przesunięcia z klastra 3 → 2
cluster3_to_2 = []

# Lista krajów do przesunięcia z klastra 3 lub 2 → 1
to_cluster1 = [
    'Philippines', 'Bahamas, The', 'Trinidad and Tobago', 'St. Lucia', 'Costa Rica', 'Panama','St. Vincent and the Grenadines', 'Ghana', 'Uganda','Dominican Republic','El Salvador','Ecuador','Jamaica', 'Mauritius','Barbados'
]

# Aktualizacja klastra: 3 → 2
clusters_all02.loc[
    (clusters_all02['year'] == 2024) &
    (clusters_all02['country_i'].isin(cluster3_to_2)) &
    (clusters_all02['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2024) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 → 2
clusters_all02.loc[
    (clusters_all02['year'] == 2023) &
    (clusters_all02['country_i'].isin(cluster3_to_2)) &
    (clusters_all02['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2023) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 → 2
clusters_all02.loc[
    (clusters_all02['year'] == 2022) &
    (clusters_all02['country_i'].isin(cluster3_to_2)) &
    (clusters_all02['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2022) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 → 2
clusters_all02.loc[
    (clusters_all02['year'] == 2021) &
    (clusters_all02['country_i'].isin(cluster3_to_2)) &
    (clusters_all02['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2021) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 → 2
clusters_all02.loc[
    (clusters_all02['year'] == 2020) &
    (clusters_all02['country_i'].isin(cluster3_to_2)) &
    (clusters_all02['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2020) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 → 2
clusters_all02.loc[
    (clusters_all02['year'] == 2019) &
    (clusters_all02['country_i'].isin(cluster3_to_2)) &
    (clusters_all02['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2019) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 → 2
clusters_all02.loc[
    (clusters_all02['year'] == 2018) &
    (clusters_all02['country_i'].isin(cluster3_to_2)) &
    (clusters_all02['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2018) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 → 2
clusters_all02.loc[
    (clusters_all02['year'] == 2017) &
    (clusters_all02['country_i'].isin(cluster3_to_2)) &
    (clusters_all02['cluster_g_3'] == 3),
    'cluster_g_3'
] = 2

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2017) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2016) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2015) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2014) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2013) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2012) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2011) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2010) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2009) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

# Aktualizacja klastra: 3 lub 2 → 1
clusters_all02.loc[
    (clusters_all02['year'] == 2008) &
    (clusters_all02['country_i'].isin(to_cluster1)) &
    (clusters_all02['cluster_g_3'].isin([2, 3])),
    'cluster_g_3'
] = 1

In [322]:
# Wypisz kraje z NaN w klastrze
nan_countries = clusters_all01[
    clusters_all01['cluster_g_3'].isna()
]['country_i'].unique().tolist()

print("Kraje z brakującym przypisaniem do klastra:")
for country in nan_countries:
    print(country)

# Usuń wiersze z NaN w cluster_g_3
#clusters_all01 = clusters_all01.dropna(subset=['cluster_g_3']).reset_index(drop=True)

Kraje z brakującym przypisaniem do klastra:
Haiti
Iraq
Serbia
South Sudan
Sudan
Timor-Leste
Vanuatu
Venezuela, RB

In [325]:
manual_clusters = {
    'Iraq': 2,
    'Serbia': 2,
    'South Sudan': 1,
    'Sudan': 1,
    'Timor-Leste': 1,
    'Vanuatu': 1,
    'Venezuela, RB': 2
}
clusters_all01['cluster_g_3'] = clusters_all01.apply(
    lambda row: manual_clusters.get(row['country_i'], row['cluster_g_3']),
    axis=1
)

In [323]:
# Oblicz procent NaN dla każdego kraju
nan_per_country = (
    clusters_all01
    .set_index('country_i')
    .isna()
    .groupby('country_i')
    .mean()
    .mean(axis=1)
    .sort_values(ascending=False) * 100
).round(2)

# Wyświetl top 10 krajów z największym procentem braków
pd.set_option('display.max_rows', None) 
nan_per_country

country_i
Venezuela, RB                     8.90
South Sudan                       8.74
Iraq                              8.27
Vanuatu                           8.27
Timor-Leste                       8.27
Serbia                            8.27
Haiti                             8.27
Sudan                             2.11
Myanmar                           0.16
Namibia                           0.16
Nepal                             0.16
Netherlands                       0.16
New Zealand                       0.16
Nicaragua                         0.16
Afghanistan                       0.16
Nigeria                           0.16
North Macedonia                   0.16
Oman                              0.16
Pakistan                          0.16
Panama                            0.16
Papua New Guinea                  0.16
Paraguay                          0.16
Peru                              0.16
Philippines                       0.16
Norway                            0.16
Morocco                           0.16
Mozambique                        0.16
Maldives                          0.16
Lesotho                           0.16
Libya                             0.16
Lithuania                         0.16
Luxembourg                        0.16
Madagascar                        0.16
Malawi                            0.16
Malaysia                          0.16
Mali                              0.16
Portugal                          0.16
Malta                             0.16
Mauritania                        0.16
Mauritius                         0.16
Mexico                            0.16
Moldova                           0.16
Mongolia                          0.16
Montenegro                        0.16
Poland                            0.16
Russian Federation                0.16
Qatar                             0.16
Uganda                            0.16
Tajikistan                        0.16
Tanzania                          0.16
Thailand                          0.16
Togo                              0.16
Trinidad and Tobago               0.16
Tunisia                           0.16
Turkiye                           0.16
Ukraine                           0.16
Romania                           0.16
United Arab Emirates              0.16
United Kingdom                    0.16
United States                     0.16
Uruguay                           0.16
Viet Nam                          0.16
Yemen, Rep.                       0.16
Zambia                            0.16
Switzerland                       0.16
Sweden                            0.16
Suriname                          0.16
St. Vincent and the Grenadines    0.16
Latvia                            0.16
Rwanda                            0.16
Samoa                             0.16
Sao Tome and Principe             0.16
Saudi Arabia                      0.16
Senegal                           0.16
Sierra Leone                      0.16
Singapore                         0.16
Slovak Republic                   0.16
Slovenia                          0.16
Solomon Islands                   0.16
South Africa                      0.16
Spain                             0.16
Sri Lanka                         0.16
St. Lucia                         0.16
Lebanon                           0.16
Lao PDR                           0.16
Albania                           0.16
Czechia                           0.16
Brunei Darussalam                 0.16
Bulgaria                          0.16
Burkina Faso                      0.16
Burundi                           0.16
Cabo Verde                        0.16
Cambodia                          0.16
Cameroon                          0.16
Canada                            0.16
Chile                             0.16
China                             0.16
Colombia                          0.16
Comoros                           0.16
Congo, Dem. Rep.                  0.16
Congo, Rep.                       0.16
Costa Rica                        0.16
Cote d'Ivoire                     0.16
Croatia                           0.16
Brazil                            0.16
Botswana                          0.16
Bosnia and Herzegovina            0.16
Bahamas, The                      0.16
Algeria                           0.16
Angola                            0.16
Argentina                         0.16
Armenia                           0.16
Australia                         0.16
Austria                           0.16
Azerbaijan                        0.16
Bahrain                           0.16
Bolivia                           0.16
Bangladesh                        0.16
Barbados                          0.16
Belarus                           0.16
Belgium                           0.16
Belize                            0.16
Benin                             0.16
Bhutan                            0.16
Cyprus                            0.16
Denmark                           0.16
Kyrgyz Republic                   0.16
Djibouti                          0.16
Honduras                          0.16
Hong Kong SAR, China              0.16
Hungary                           0.16
Iceland                           0.16
India                             0.16
Indonesia                         0.16
Iran, Islamic Rep.                0.16
Ireland                           0.16
Israel                            0.16
Italy                             0.16
Jamaica                           0.16
Japan                             0.16
Jordan                            0.16
Kazakhstan                        0.16
Kenya                             0.16
Korea, Rep.                       0.16
Kuwait                            0.16
Guyana                            0.16
Guinea-Bissau                     0.16
Guinea                            0.16
Fiji                              0.16
Dominican Republic                0.16
Ecuador                           0.16
Egypt, Arab Rep.                  0.16
El Salvador                       0.16
Estonia                           0.16
Eswatini                          0.16
Ethiopia                          0.16
Finland                           0.16
Guatemala                         0.16
France                            0.16
Gabon                             0.16
Gambia, The                       0.16
Georgia                           0.16
Germany                           0.16
Ghana                             0.16
Greece                            0.16
Zimbabwe                          0.16
dtype: float64

In [332]:
data_countries = set(clusters_all01['country_i'].unique())
empl_countries = set(serv_va_us['country_i'].unique())

data_only = data_countries - empl_countries
empl_only = empl_countries - data_countries

# Znajdź dopasowane nazwy krajów
common_countries = data_countries.intersection(empl_countries)
print(f"Dopasowane nazwy krajów ({len(common_countries)}):")
print(sorted(common_countries))


print(f"\nNazwy krajów tylko w zbiorze 'data' ({len(data_only)}):")
print(sorted(data_only))

print(f"\nNazwy krajów tylko w zbiorze 'merged' ({len(empl_only)}):")
print(sorted(empl_only))

Dopasowane nazwy krajów (166):
['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Korea, Rep.', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Latvia', 'Lebanon', 'Lesotho', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia', 'Solomon Islands', 'South Africa', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Lucia', 'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Vanuatu', 'Venezuela, RB', 'Viet Nam', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']

Nazwy krajów tylko w zbiorze 'data' (0):
[]

Nazwy krajów tylko w zbiorze 'merged' (51):
['American Samoa', 'Andorra', 'Antigua and Barbuda', 'Aruba', 'Bermuda', 'British Virgin Islands', 'Cayman Islands', 'Central African Republic', 'Chad', 'Channel Islands', 'Cuba', 'Curacao', 'Dominica', 'Equatorial Guinea', 'Eritrea', 'Faroe Islands', 'French Polynesia', 'Gibraltar', 'Greenland', 'Grenada', 'Guam', 'Isle of Man', 'Kiribati', "Korea, Dem. People's Rep.", 'Kosovo', 'Liberia', 'Liechtenstein', 'Macao SAR, China', 'Marshall Islands', 'Micronesia, Fed. Sts.', 'Monaco', 'Nauru', 'New Caledonia', 'Niger', 'Northern Mariana Islands', 'Palau', 'Puerto Rico', 'San Marino', 'Seychelles', 'Sint Maarten (Dutch part)', 'Somalia', 'St. Kitts and Nevis', 'St. Martin (French part)', 'Syrian Arab Republic', 'Tonga', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uzbekistan', 'Virgin Islands (U.S.)', 'West Bank and Gaza']

In [333]:
wd = pd.read_csv('/Users/weronika/Desktop/DELab/1b5e559d-67ba-4b51-aa0e-99961cd03ef4_Data.csv')
wd = wd.dropna(subset=['Country Name'])
wd = wd.rename(columns={'Country Name':'country_i', 'Time':'year'}).drop(['Series Code', 'Time Code','Country Code'], axis=1)
serv_va_us = wd[wd['Series Name'] == 'Services, value added (current US$)']
serv_va_us = serv_va_us.rename(columns={'Value':'serv_va_us'}).drop(['Series Name'], axis=1)
kraje_serv = ['American Samoa', 'Andorra', 'Antigua and Barbuda', 'Aruba', 'Bermuda', 'British Virgin Islands', 'Cayman Islands', 'Central African Republic', 'Chad', 'Channel Islands', 'Cuba', 'Curacao', 'Dominica', 'Equatorial Guinea', 'Eritrea', 'Faroe Islands', 'French Polynesia', 'Gibraltar', 'Greenland', 'Grenada', 'Guam', 'Isle of Man', 'Kiribati', "Korea, Dem. People's Rep.", 'Kosovo', 'Liberia', 'Liechtenstein', 'Macao SAR, China', 'Marshall Islands', 'Micronesia, Fed. Sts.', 'Monaco', 'Nauru', 'New Caledonia', 'Niger', 'Northern Mariana Islands', 'Palau', 'Puerto Rico', 'San Marino', 'Seychelles', 'Sint Maarten (Dutch part)', 'Somalia', 'St. Kitts and Nevis', 'St. Martin (French part)', 'Syrian Arab Republic', 'Tonga', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uzbekistan', 'Virgin Islands (U.S.)', 'West Bank and Gaza']
serv_va_us01 = serv_va_us[~serv_va_us['country_i'].isin(kraje_serv)]
clusters_all02 = pd.merge(clusters_all01,serv_va_us01, on=['country_i','year'], how='left')
clusters_all02['serv_va_per_pop'] = clusters_all02['serv_va_us'] / clusters_all02['population']

In [327]:
clusters_all01[
    clusters_all01['year'] == 2014
][['country_i', 'classification', 'cluster_g_3']]

,country_i,classification,cluster_g_3
6,Afghanistan,Low-income countries,1.0
23,Albania,Upper-middle-income countries,2.0
40,Algeria,Upper-middle-income countries,1.0
57,Angola,Upper-middle-income countries,1.0
74,Argentina,High-income countries,2.0
91,Armenia,Lower-middle-income countries,1.0
108,Australia,High-income countries,3.0
125,Austria,High-income countries,3.0
142,Azerbaijan,Upper-middle-income countries,1.0
159,"Bahamas, The",High-income countries,2.0
176,Bahrain,High-income countries,2.0
193,Bangladesh,Lower-middle-income countries,1.0
210,Barbados,High-income countries,2.0
227,Belarus,Upper-middle-income countries,1.0
244,Belgium,High-income countries,3.0
261,Belize,Upper-middle-income countries,1.0
278,Benin,Low-income countries,1.0
295,Bhutan,Lower-middle-income countries,1.0
312,Bolivia,Lower-middle-income countries,1.0
329,Bosnia and Herzegovina,Upper-middle-income countries,2.0
346,Botswana,Upper-middle-income countries,1.0
363,Brazil,Upper-middle-income countries,2.0
380,Brunei Darussalam,High-income countries,1.0
397,Bulgaria,Upper-middle-income countries,2.0
414,Burkina Faso,Low-income countries,1.0
431,Burundi,Low-income countries,1.0
448,Cabo Verde,Lower-middle-income countries,2.0
465,Cambodia,Low-income countries,1.0
482,Cameroon,Lower-middle-income countries,1.0
499,Canada,High-income countries,3.0
516,Chile,High-income countries,2.0
533,China,Upper-middle-income countries,3.0
550,Colombia,Upper-middle-income countries,2.0
567,Comoros,Low-income countries,1.0
584,"Congo, Dem. Rep.",Low-income countries,1.0
601,"Congo, Rep.",Lower-middle-income countries,1.0
618,Costa Rica,Upper-middle-income countries,3.0
635,Cote d'Ivoire,Lower-middle-income countries,1.0
652,Croatia,High-income countries,2.0
669,Cyprus,High-income countries,2.0
686,Czechia,High-income countries,3.0
703,Denmark,High-income countries,3.0
720,Djibouti,Lower-middle-income countries,1.0
737,Dominican Republic,Upper-middle-income countries,2.0
754,Ecuador,Upper-middle-income countries,2.0
771,"Egypt, Arab Rep.",Lower-middle-income countries,1.0
788,El Salvador,Lower-middle-income countries,1.0
805,Estonia,High-income countries,3.0
822,Eswatini,Lower-middle-income countries,1.0
839,Ethiopia,Low-income countries,1.0
856,Fiji,Upper-middle-income countries,1.0
873,Finland,High-income countries,3.0
890,France,High-income countries,3.0
907,Gabon,Upper-middle-income countries,1.0
924,"Gambia, The",Low-income countries,1.0
941,Georgia,Lower-middle-income countries,2.0
958,Germany,High-income countries,3.0
975,Ghana,Lower-middle-income countries,1.0
992,Greece,High-income countries,2.0
1009,Guatemala,Lower-middle-income countries,1.0
1026,Guinea,Low-income countries,1.0
1043,Guinea-Bissau,Low-income countries,1.0
1060,Guyana,Lower-middle-income countries,1.0
1077,Haiti,Low-income countries,NaN
1094,Honduras,Lower-middle-income countries,1.0
1111,"Hong Kong SAR, China",High-income countries,3.0
1128,Hungary,High-income countries,3.0
1145,Iceland,High-income countries,3.0
1162,India,Lower-middle-income countries,1.0
1179,Indonesia,Lower-middle-income countries,1.0
1196,"Iran, Islamic Rep.",Upper-middle-income countries,1.0
1213,Iraq,Upper-middle-income countries,2.0
1230,Ireland,High-income countries,3.0
1247,Israel,High-income countries,3.0
1264,Italy,High-income countries,2.0
1281,Jamaica,Upper-middle-income countries,2.0
1298,Japan,High-income countries,3.0
1315,Jordan,Upper-middle-income countries,2.0
1332,Kazakhstan,Upper-middle-income countries,2.0
1349,Kenya,Lower-middle-income countries,2.0
1366,"Korea, Rep.",High-income countries,3.0
1383,Kuwait,High-income countries,1.0
1400,Kyrgyz Republic,Lower-middle-income countries,1.0
1417,Lao PDR,Lower-middle-income countries,1.0
1434,Latvia,High-income countries,2.0
1451,Lebanon,Upper-middle-income countries,1.0
1468,Lesotho,Lower-middle-income countries,1.0
1485,Libya,Upper-middle-income countries,1.0
1502,Lithuania,High-income countries,2.0
1519,Luxembourg,High-income countries,3.0
1536,Madagascar,Low-income countries,1.0
1553,Malawi,Low-income countries,1.0
1570,Malaysia,Upper-middle-income countries,2.0
1587,Maldives,Upper-middle-income countries,1.0
1604,Mali,Low-income countries,1.0
1621,Malta,High-income countries,3.0
1638,Mauritania,Lower-middle-income countries,1.0
1655,Mauritius,Upper-middle-income countries,2.0
1672,Mexico,Upper-middle-income countries,2.0
1689,Moldova,Lower-middle-income countries,2.0
1706,Mongolia,Upper-middle-income countries,1.0
1723,Montenegro,Upper-middle-income countries,2.0
1740,Morocco,Lower-middle-income countries,2.0
1757,Mozambique,Low-income countries,1.0
1774,Myanmar,Lower-middle-income countries,1.0
1791,Namibia,Upper-middle-income countries,1.0
1808,Nepal,Low-income countries,1.0
1825,Netherlands,High-income countries,3.0
1842,New Zealand,High-income countries,3.0
1859,Nicaragua,Lower-middle-income countries,1.0
1876,Nigeria,Lower-middle-income countries,1.0
1893,North Macedonia,Upper-middle-income countries,2.0
1910,Norway,High-income countries,3.0
1927,Oman,High-income countries,2.0
1944,Pakistan,Lower-middle-income countries,1.0
1961,Panama,Upper-middle-income countries,2.0
1978,Papua New Guinea,Lower-middle-income countries,1.0
1995,Paraguay,Upper-middle-income countries,1.0
2012,Peru,Upper-middle-income countries,2.0
2029,Philippines,Lower-middle-income countries,1.0
2046,Poland,High-income countries,2.0
2063,Portugal,High-income countries,2.0
2080,Qatar,High-income countries,2.0
2097,Romania,Upper-middle-income countries,2.0
2114,Russian Federation,High-income countries,1.0
2131,Rwanda,Low-income countries,1.0
2148,Samoa,Lower-middle-income countries,1.0
2165,Sao Tome and Principe,Lower-middle-income countries,1.0
2182,Saudi Arabia,High-income countries,2.0
2199,Senegal,Lower-middle-income countries,1.0
2216,Serbia,Upper-middle-income countries,2.0
2233,Sierra Leone,Low-income countries,1.0
2250,Singapore,High-income countries,3.0
2267,Slovak Republic,High-income countries,2.0
2284,Slovenia,High-income countries,2.0
2301,Solomon Islands,Lower-middle-income countries,1.0
2318,South Africa,Upper-middle-income countries,2.0
2341,South Sudan,Low-income countries,1.0
2342,South Sudan,Low-income countries,1.0
2369,Spain,High-income countries,2.0
2386,Sri Lanka,Lower-middle-income countries,1.0
2403,St. Lucia,Upper-middle-income countries,2.0
2420,St. Vincent and the Grenadines,Upper-middle-income countries,2.0
2443,Sudan,Lower-middle-income countries,1.0
2444,Sudan,Lower-middle-income countries,1.0
2469,Suriname,Upper-middle-income countries,1.0
2486,Sweden,High-income countries,3.0
2503,Switzerland,High-income countries,3.0
2520,Tajikistan,Lower-middle-income countries,1.0
2537,Tanzania,Low-income countries,1.0
2554,Thailand,Upper-middle-income countries,3.0
2571,Timor-Leste,Lower-middle-income countries,1.0
2588,Togo,Low-income countries,1.0
2605,Trinidad and Tobago,High-income countries,2.0
2622,Tunisia,Upper-middle-income countries,2.0
2639,Turkiye,Upper-middle-income countries,2.0
2656,Uganda,Low-income countries,2.0
2673,Ukraine,Lower-middle-income countries,2.0
2690,United Arab Emirates,High-income countries,2.0
2707,United Kingdom,High-income countries,3.0
2724,United States,High-income countries,3.0
2741,Uruguay,High-income countries,2.0
2758,Vanuatu,Lower-middle-income countries,1.0
2775,"Venezuela, RB",High-income countries,2.0
2792,Viet Nam,Lower-middle-income countries,3.0
2809,"Yemen, Rep.",Lower-middle-income countries,1.0
2826,Zambia,Lower-middle-income countries,1.0
2843,Zimbabwe,Low-income countries,1.0

In [170]:
clusters_all01[clusters_all01['country_i'] == 'United States']

,country_i,year,ftri_total_i,ftri_ict_i,ftri_skills_i,ftri_rd_i,ftri_ind_i,ftri_finance_i,ftri_total_i_s,ftri_ict_i_s,...,iso3_o,reg_score,classification,broadband_i,internet_users_i,secure_servers_i,cluster_g_3,cluster_g_4,cluster_g_5,income
3321,United States,2008,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,77100000.0,74.00000,2.182804e+07,3.0,2.0,1.0,High-income countries
3322,United States,2009,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,80000000.0,71.00000,2.182804e+07,3.0,2.0,1.0,High-income countries
3323,United States,2010,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,84500000.0,71.70000,7.676620e+05,3.0,2.0,1.0,High-income countries
3324,United States,2011,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,88300000.0,69.70000,9.304710e+05,3.0,2.0,1.0,High-income countries
3325,United States,2012,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,92500000.0,74.70000,1.205823e+06,3.0,2.0,1.0,High-income countries
3326,United States,2013,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,96000000.0,71.40000,1.360046e+06,3.0,2.0,1.0,High-income countries
3327,United States,2014,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,97800000.0,73.00000,1.633177e+06,3.0,2.0,1.0,High-income countries
3328,United States,2015,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,102000000.0,74.60000,2.039539e+06,3.0,2.0,1.0,High-income countries
3329,United States,2016,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,106000000.0,85.50000,3.694357e+06,3.0,2.0,1.0,High-income countries
3330,United States,2017,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,108000000.0,87.30000,9.863566e+06,3.0,2.0,1.0,High-income countries
3331,United States,2018,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,111000000.0,88.50000,2.151700e+07,3.0,2.0,1.0,High-income countries
3332,United States,2019,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,114000000.0,89.40000,4.070635e+07,3.0,2.0,1.0,High-income countries
3333,United States,2020,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,121000000.0,90.30000,4.667811e+07,3.0,2.0,1.0,High-income countries
3334,United States,2021,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,126000000.0,91.30000,5.212287e+07,3.0,2.0,1.0,High-income countries
3335,United States,2022,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,128000000.0,92.20000,6.019428e+07,3.0,2.0,1.0,High-income countries
3336,United States,2023,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,131000000.0,93.10000,6.287934e+07,3.0,2.0,1.0,High-income countries
3337,United States,2024,0.461799,0.434339,0.463896,0.2485,0.562338,0.668947,0.040816,0.035167,...,NaN,67.09724,NaN,103950000.0,81.10625,2.182804e+07,3.0,2.0,1.0,NaN